name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/determinate-nix-action@v3.11.2
      - uses: DeterminateSystems/update-flake-lock@v27
        with:
          pr-title: Update Nix flake inputs
          pr-labels: |
            dependencies
            automated
          sign-commits: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          git-author-name: pinguibot
          git-author-email: bot@pingui.org
          git-committer-name: pinguibot
          git-committer-email: bot@pingui.org
